### PR TITLE
added support for the jquery.dataTables.columnFilter plugin

### PR DESCRIPTION
**Pull request by AlexKeySmith**
I've added some basic support for filtering via the jquery.dataTables.columnFilter plugin as discussed in issue: https://github.com/vpllan/jQuery.dataTables.oData/issues/5

I looked at parsing out all the settings in "sSearch_X" etc and grabbing the column names, types etc. However it's fortunate that the X in "sSearch_X" matches the index in oSettings.aoColumns, so I could use the existing sFieldName.

I was considering checking for number types in jquery.dataTables.columnFilter, but figured it best that they are explicitly excluded to stop columFilter during text boxes for columns that are unfilterable.

I could probably improve this by adding support for range filtering via the columnFilter and generating the appropriate oData request, but this is a good start.

It seems to work nicely so far and after trying a few options it didn't take too much code in the end, what do you think?

### CODE REVIEW

**Comment by AlexKeySmith** [comment]
Thanks @JocaPC

**Comment by JocaPC** [comment]
Thank you for adding this change. I have slightly changed your code and moved parts you have added in the case branch for text and html types (because they belong there). In other two cases (number/date) I have added code that enables date-range and number-range filters. I have tried it with reference OData service.

Thanks,
Jovan

**Comment by AlexKeySmith** [comment]
Cool, good idea @JocaPC have a nice weekend.

**Comment by worthy7** [comment]
This this ever get improved? I badly need number/boolean searches through odata

**Pull request merged**
